# Generated by Django 6.1.1 on 2026-09-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='abs_function',
            field=models.BooleanField(default=False, help_text='True for Yes, False for No'),
        ),
        migrations.AddField(
            model_name='bike',
            name='mileage',
            field=models.CharField(blank=True, help_text='e.g., 40 kmpl', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='top_speed',
            field=models.CharField(blank=True, help_text='e.g., 120 kmph', max_length=50, null=True),
        ),
    ]
